import fg from "fast-glob";
import { writeFile } from "fs/promises";
import { dirname, join, resolve } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const pkgRoot = resolve(__dirname, "..");

/**
 * Complete path helper.
 * @param {*} pathFromSrc Path under `src`.
 * @returns {string} Absolute path
 */
const completePath = (pathFromSrc: string) => {
  return join(pkgRoot, pathFromSrc);
};

const generateExportLines = async (path: string) => {
  const dirEntries = await fg("**/*.{ts,tsx}", { cwd: path });
  const entries = [...dirEntries];
  const lines = [];

  for (const file of entries) {
    const withoutExt = file.replace(/\.[tj]sx?$/, "");

    if (withoutExt === "index") {
      continue; // skip index files to avoid re-exporting from themselves
    }

    const path = `./${withoutExt}`;
    lines.push(`export * from "${path}";`);
  }

  return lines;
};

const createExportFile = async (dir: string) => {
  const dirs = [completePath(dir)];
  const outFile = join(pkgRoot, `${dir}/index.ts`);
  const lines = [];

  for (const dir of dirs) {
    const dirLines = await generateExportLines(dir);
    lines.push(...dirLines);
  }

  const header = `/* eslint-disable simple-import-sort/exports */\n/* AUTO-GENERATED by scripts/export.js */\n\n`;
  const content = header + lines.join("\n") + "\n";

  await writeFile(outFile, content, "utf8");
};

await createExportFile("components");
await createExportFile("lib");
await createExportFile("hooks");
