import fg from "fast-glob";
import { writeFile } from "fs/promises";
import { dirname, join, resolve } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const pkgRoot = resolve(__dirname, "..");

/**
 * Complete path helper.
 * @param {*} pathFromSrc Path under `src`.
 * @returns {string} Absolute path
 */
const completePath = (pathFromSrc) => {
  return join(pkgRoot, pathFromSrc);
};

const generateExportLines = async (path) => {
  // find all .ts/.tsx files in desired directories, excluding tests/stories
  const entries = [];
  const dirEntries = await fg("**/*.{ts,tsx}", {
    cwd: path,
    ignore: ["**/*.test.*", "**/*.spec.*", "**/*.stories.*", "**/__snapshots__/**"],
  });
  entries.push(...dirEntries);

  // Option A: simple export * from each file (works if each file exports named exports)
  const lines = entries.map((file) => {
    const withoutExt = file.replace(/\.[tj]sx?$/, "");
    const folder = path.split("/").pop();
    const rel = `./${folder}/${withoutExt}`;
    return `export * from '${rel}';`;
  });

  // Option B (alternative): export default as named (uncomment if your components are default exports)
  // const lines = entries.map((file) => {
  //   const name = path.basename(file).replace(/\.[tj]sx?$/, "");
  //   const pascal = name.replace(/(^\w|-\w)/g, (m) => m.replace(/-/, "").toUpperCase());
  //   const withoutExt = file.replace(/\.[tj]sx?$/, "");
  //   const rel = `./components/${withoutExt}`;
  //   return `export { default as ${pascal} } from '${rel}';`;
  // });

  return lines;
};

(async () => {
  const dirs = [completePath("components"), completePath("lib"), completePath("hooks")];
  const outFile = join(pkgRoot, "index.ts");

  const lines = [];
  for (const dir of dirs) {
    const dirLines = await generateExportLines(dir);
    lines.push(...dirLines);
  }

  const header = `/* AUTO-GENERATED by scripts/generate-exports.js — do not edit */\n\n`;
  const content = header + lines.join("\n") + "\n";
  await writeFile(outFile, content, "utf8");
})();
